-- 002_seed_data.sql
-- USER ACTION REQUIRED: Replace <YOUR_AUTH_UID> below with the UUID of your Supabase auth user
-- before running this in the Supabase SQL editor.
-- To get your UUID:
--   1. Supabase dashboard -> Authentication -> Users -> Invite user (your personal email)
--   2. Click the magic link in your inbox
--   3. Back in dashboard -> Authentication -> Users -> copy the id (UUID) of your user
insert into public.learning_weeks
  (owner_id, phase, week_label, course_title, url, time_estimate, apply_action, sort_order)
values
  ('<YOUR_AUTH_UID>', 'Phase 1 — Master your existing stack', 'Week 1',
   'Anthropic Interactive Prompt Engineering Tutorial',
   'https://github.com/anthropics/prompt-eng-interactive-tutorial',
   '~6 hrs',
   'Rewrite DARA''s worst-performing prompt using Chapter 9 structure.',
   1),
  ('<YOUR_AUTH_UID>', 'Phase 1 — Master your existing stack', 'Week 2',
   'Anthropic Courses repo (real_world_prompting + prompt_evaluations) + Academy',
   'https://github.com/anthropics/courses',
   '~6 hrs',
   'Add an eval harness to one Pipeline Guardian decision.',
   2),
  ('<YOUR_AUTH_UID>', 'Phase 2 — LLM systems engineering', 'Week 3',
   'DeepLearning.AI — Building and Evaluating Advanced RAG',
   'https://www.deeplearning.ai/short-courses/building-evaluating-advanced-rag',
   '~2 hrs',
   'Sketch a RAG layer over analytics views for DARA.',
   3),
  ('<YOUR_AUTH_UID>', 'Phase 2 — LLM systems engineering', 'Week 4',
   'DeepLearning.AI — Evaluating AI Agents',
   'https://learn.deeplearning.ai/courses/evaluating-ai-agents/information',
   '~2 hrs',
   'Add observability traces to Pipeline Guardian.',
   4),
  ('<YOUR_AUTH_UID>', 'Phase 2 — LLM systems engineering', 'Week 5',
   'DeepLearning.AI — Functions, Tools and Agents with LangChain',
   'https://www.deeplearning.ai/courses/functions-tools-agents-langchain',
   '~3 hrs',
   'Re-read Pipeline Guardian tools through the LCEL lens.',
   5),
  ('<YOUR_AUTH_UID>', 'Phase 3 — Modern data stack', 'Week 6',
   'dbt Learn — dbt Fundamentals',
   'https://learn.getdbt.com/courses/dbt-fundamentals',
   '~5 hrs',
   'Spin up dbt-postgres against Supabase.',
   6),
  ('<YOUR_AUTH_UID>', 'Phase 3 — Modern data stack', 'Week 7',
   'Apply dbt to Report Automation (no new course)',
   'https://learn.getdbt.com/catalog',
   '~5 hrs',
   'Convert one Report Automation query into a dbt model with tests + sources.',
   7),
  ('<YOUR_AUTH_UID>', 'Phase 3 — Modern data stack', 'Week 8',
   'Astronomer Academy — Airflow 101 Learning Path',
   'https://academy.astronomer.io/path/airflow-101',
   '~6 hrs',
   'Redraw pipeline.yml as an Airflow DAG.',
   8),
  ('<YOUR_AUTH_UID>', 'Phase 4 — Cloud + GenAI fluency', 'Week 9',
   'Google Cloud Skills Boost — Generative AI Leader Learning Path',
   'https://cloud.google.com/learn/certification/generative-ai-leader',
   '~6 hrs',
   'List three GCP services to swap for current Supabase/GHA components.',
   9),
  ('<YOUR_AUTH_UID>', 'Phase 4 — Cloud + GenAI fluency', 'Week 10',
   'Architecture rewrite exercise (no new course)',
   'https://cloud.google.com/architecture',
   '~3 hrs',
   'Whiteboard DARA-on-GCP architecture diagram.',
   10),
  ('<YOUR_AUTH_UID>', 'Phase 5 — Optional depth', 'Week 11+',
   'Hugging Face — AI Agents Course',
   'https://huggingface.co/learn/agents-course/en/unit0/introduction',
   'multi-week',
   'Pick one of the three depth tracks.',
   11),
  ('<YOUR_AUTH_UID>', 'Phase 5 — Optional depth', 'Week 11+',
   'Made With ML — MLOps Course',
   'https://madewithml.com/courses/mlops/',
   'multi-month',
   'Optional production-ML rigor.',
   12),
  ('<YOUR_AUTH_UID>', 'Phase 5 — Optional depth', 'Week 11+',
   'Hugging Face — LLM Course',
   'https://huggingface.co/learn/llm-course/en/chapter1/1',
   'multi-week',
   'Optional transformer internals.',
   13),
  ('<YOUR_AUTH_UID>', 'Capstone', 'Capstone',
   'Public writeup: Pipeline Guardian or DARA',
   '',
   '',
   'After Week 10, publish a writeup with architecture diagram, eval harness, RAG/agent vocab, GCP comparison.',
   999);
